### ISSUE TITLE
Implementar criação de novo funcionário

### ISSUE THREAD

**Issue by NatanVini7** [marcosdosea/gcm-ufs#1018]
Implementar a criação de um novo funcionário recebendo novos dados

**Comment by Felip3D3V** [comment]
Definir a Estrutura do Método:

Criar um método criarFuncionario na classe GerenciadorFuncionarios que receberá os dados do novo funcionário.
Os dados recebidos incluirão nome, cargo, e salário.
Verificações e Validações:

Validar se todos os campos são preenchidos corretamente.
Verificar se o salário é um valor positivo.
Adicionar o Novo Funcionário à Lista:

Criar um objeto Funcionario com os dados recebidos.
Adicionar o objeto Funcionario à lista de funcionários.
