### ISSUE TITLE
Implementar método inserir no GerenciadorVendas

### ISSUE THREAD

**Issue by edutvares** [marcosdosea/gcm-ufs#1023]

**Comment by Felip3D3V** [comment]
Passos para Implementação:
Definir a Estrutura do Método:

O método inserir receberá um objeto Venda como parâmetro.
O método irá adicionar esse objeto à lista interna de vendas.
Verificações e Validações:

Verificar se o objeto Venda não é null.
Adicionar verificações para garantir que a venda não é duplicada (opcional, dependendo dos requisitos).
Atualizar a Lista de Vendas:

Adicionar a nova venda à lista de vendas da classe.
