### ISSUE TITLE
Corrigir notação UML no Diagrama de Caso de  Uso

### ISSUE THREAD

**Issue by marcosdosea** [marcosdosea/gcm-ufs#1200]
1. Alterar nome de casos de uso para usar verbos no inifinito
2. remover relacionamento de herança entre atores

**Comment by IGOR1630** [comment]
Ok, irei ajeitar isso

**Comment by IGOR1630** [comment]
Nome dos casos de uso alterados para verbos no infinitivo e remoção dos relacionamentos feitas
