### ISSUE TITLE
Corrigir Admissão Residente 

### ISSUE THREAD

**Issue by GhostRes** [marcosdosea/gcm-ufs#1201]
@IGOR1630 

1-corrigirr tela do usuário

**Comment by IGOR1630** [comment]
Ok, meu querido

**Comment by marcosdosea** [comment]
@GhostRes não consegui replicar o problema.

**Comment by GhostRes** [comment]
O problema está localizado na interface

**Comment by marcosdosea** [comment]
Ok. Problema resolvido.
