### ISSUE TITLE
Implementar autenticação por dois fatores (2FA)

### ISSUE THREAD

**Issue by Guilherme-Yeager** [marcosdosea/gcm-ufs#1211]
Para trazer mais segurança para nossos clientes, sugiro que na tela de login de usuário haja uma opção para que o usuário possa acessar o sistema através de dois fatores, protegendo ainda mais a sua conta. Assim, se o usuário preferir, após inserir suas credenciais (usuário e senha) corretamente, deve ser solicitado um segundo fator de autenticação, esse segundo fator de autenticação pode ser uma confirmação enviada para o e-mail cadastrado do usuário.

**Comment by Fashion-Q** [comment]
Implementamos a opção de autenticação de dois fatores (2FA) na tela de login. Após inserir as credenciais, o sistema agora envia um código de verificação para o e-mail cadastrado do usuário. No entanto, tivemos alguns problemas durante a implementação:

Configuração do Servidor de E-mail: Tivemos dificuldades para configurar o servidor de e-mail para enviar os códigos de verificação de forma consistente. Algumas mensagens de e-mail estavam sendo marcadas como spam, e outras não estavam sendo entregues.

Interface de Usuário: Inicialmente, a interface para inserir o código de verificação não era intuitiva. Recebemos feedback dos usuários de que o processo era confuso e exigia muitas etapas. Fizemos algumas melhorias na interface para torná-la mais clara e direta.
