### ISSUE TITLE
Adicionar novos temas de cores

### ISSUE THREAD

**Issue by Guilherme-Yeager** [marcosdosea/gcm-ufs#1212]
O sistema atualmente só possui uma paleta de cores padrão.
Sugiro que adicione mais temas para que nossos clientes possa escolher como queira a interface naquele momento, por exemplo, "Dark". Assim, é possível passar mais conforto para nossos clientes.

**Comment by Fashion-Q** [comment]
Concordo que adicionar mais temas, como o "Dark", pode melhorar a experiência dos nossos clientes. Adicionei também uma versão Light Blue e Ciano. Enfrentei alguns desafios com a compatibilidade dos componentes e a persistência das preferências do usuário. Estamos trabalhando para resolver esses problemas e atualizar o Documento de Visão para refletir essas mudanças.
