### ISSUE TITLE
Corrigir componente da interface

### ISSUE THREAD

**Issue by Guilherme-Yeager** [marcosdosea/gcm-ufs#1215]
Devido ao um novo componente adicionado no navbar (botão de home), na medida em que a página muda de resolução o componente fica sobre a logo do sistema. É necessário corrigir isto para garantir a responsividade da página.

**Comment by Fashion-Q** [comment]
Corrigido! Foi devido a um evento do javaScript navHamburguer.addEventListener("click", () => nav.classList.toggle("active"));  Estava mudando o comportamento para Absolute.
