### ISSUE TITLE
Implementar correção na interface do cadastro do cliente

### ISSUE THREAD

**Issue by imarcossm** [marcosdosea/gcm-ufs#1234]
Está ocorrendo problema na interface do cadastro do cliente, onde se ele for contribuinte de ICMS a opção de selecionar está em branco.

**Comment by K4U4dev** [comment]
Corrigida essa problemática na combo box de seleção do tipo de contribuinte. Agora abrange também o tipo "Contribuinte de ICMS" e foi desabilitada a opção de "contribuinte ISENTO" que já não está mais em uso.
