### ISSUE TITLE
Criar funcionalidade de referenciar nota fiscal de origem nas devoluções

### ISSUE THREAD

**Issue by imarcossm** [marcosdosea/gcm-ufs#1235]
É necessário perante padrões fiscais que nas necessidades de fazer nota fiscal de devolução, o emitente referencie a nota fiscal de origem em questão. Sugiro criar a funcionalidade para que agilize o processo dos clientes.

**Comment by K4U4dev** [comment]
Foi criada a funcionalidade de referenciar nota fiscal de origem nas devoluções
