### ISSUE TITLE
Criar seleção de tipos de pessoa física ou jurídica

### ISSUE THREAD

**Issue by imarcossm** [marcosdosea/gcm-ufs#1237]
Os clientes podem ser de tipos variados, sendo em sua maioria pessoa física (cpf) ou jurídica (cnpj). Sugiro que o cliente independente do tipo possa ser cadastrado na aplicação com informações verídicas.

**Comment by K4U4dev** [comment]
Foi adicionado um verificador da validade do CPF ou CNPJ que for informado no campo, a máscara só é aplicada na exibição, os dados estão sendo armazenados no banco como cadeia de caracteres e somente a numeração. Dependendo do tamanho da string, se validada, o programa já identifica se é uma pessoa física ou jurídica.
