### ISSUE TITLE
Corrigir a entrada de notas

### ISSUE THREAD

**Issue by K4U4dev** [marcosdosea/gcm-ufs#1240]
No momento de importar um xml na aplicação, está sendo exibido o CFOP 5102 na listagem dos detalhes dos produtos. Não deve ser assim, tendo em vista que esse CFOP é destinado a venda de mercadoria adquirida ou recebida de terceiros.

**Comment by imarcossm** [comment]
Corrigido o problema referente ao CFOP de saída através de um pequeno ajuste na função responsável pela conversão do código. Agora identificando: 6 (saída fora do estado) correspondente a 2 (compra de fora do estado), e 5 (saída dentro do estado) correspondente a 1 (compra dentro do próprio estado).
