### ISSUE TITLE
Corrigir a mudança de tema da aplicação

### ISSUE THREAD

**Issue by K4U4dev** [marcosdosea/gcm-ufs#1241]
No ato de clicar no botão de alterar o tema da aplicação, quanto é selecionado o tema escuro está sendo baixado o brilho do dispositivo, em vez de mudar as cores da aplicação para uma paleta de cores escuras. Ao clicar em tema claro o brilho do dispositivo está sendo definido em 100%. Isso não faz sentido para o funcionamento e objetivos da funcionalidade.

**Comment by imarcossm** [comment]
Corrigida a inversão do tema claro para o escuro e vice-versa utilizando a propriedade correta da biblioteca ao invés da que foi implementada anteriomente. Da forma que estava, alterava as configurações de exibição da máquina mexendo apenas no brilho, ao invés de ativar a propriedade de paletas claras e escuras.
