### ISSUE TITLE
Corrigir evento de geração de relatório

### ISSUE THREAD

**Issue by K4U4dev** [marcosdosea/gcm-ufs#1244]
Ao clicar no botão de gerar o relatório de vendas a aplicação está fechando, isso não é legal. Deve verificar se há algum erro de tratamento de exceção.

**Comment by imarcossm** [comment]
Corrigido o problema no tratamento da exceção de erro da ausência de dados do relatório e inserido um novo bloco global que captura exceções não tratadas.
