### ISSUE TITLE
Email inválido pode ser usado no cadastro de usuário

### ISSUE THREAD

**Issue by Eldeerick** [marcosdosea/gcm-ufs#168]
Emails que não possuem a regex correta podem ser utilizados no cadastro de usuário, podendo resultar em erros caso o mesmo seja utilizado.

**Comment by luizmoitinho** [comment]
O regex não estava sendo aplicado corretamente, ocorreu uma correção na sua expressão regular, para que assim, não seja permitido admitir e-mail que não se adequam ao padrão. Bem como adicionado uma nova validação no back-end.
