### ISSUE TITLE
Adicionar o campo "Em andamento" no momento em que for acompanhar uma ocorrência.

### ISSUE THREAD

**Issue by luizmoitinho** [marcosdosea/gcm-ufs#170]
Solicito que na rotina de edição de uma ocorrência cadastrada no sistema, seja adicionado uma nova opção para que seja alterado assim que um agente de segurança der inicio ao andamento da ocorrência. Da forma como está, utilizamos o termo "Em análise" para isso, o que acaba gerando confusão nos usuários acerca do andamento.

**Comment by GCaio7** [comment]
Nova coluna adicionada à tabela de ocorrências
