### ISSUE TITLE
Sistema falha ao tentar emprestar mais de três livros simultaneamente

### ISSUE THREAD

**Issue by marcosdosea** [marcosdosea/gcm-ufs#2]
Na tela de empréstimo de livros, ao inserir mais de três livros distintos para empréstimo, o sistema informa a mensagem "Falha geral do sistema, por favor contacte o administrador."

**Comment by marcosdosea** [comment]
Preciso criar um campo no banco de dados

**Comment by Clovijan** [comment]
@marcosdosea  o campo já está criado

**Comment by marcosdosea** [comment]
Fix #2
