### ISSUE TITLE
O sistema não envia o e-mail para recuperação de senha

### ISSUE THREAD

**Issue by joaoalvescs** [marcosdosea/gcm-ufs#20]
O usuário solicita a redefinição de senha e o e-mail contendo um link temporário para trocar a senha não é enviado para o e-mail do destinatário.

**Comment by Kamila-lima** [comment]
@joaoalvescs #20 fix

**Comment by Kamila-lima** [comment]
f

**Comment by Kamila-lima** [comment]
fix #20
