### ISSUE TITLE
versão mobile com bug

### ISSUE THREAD

**Issue by IgorSantos1996** [marcosdosea/gcm-ufs#22]
Para a versão mobile do sistema,  o botão de renovação de livros, não está funcionando como deveria, nem tampouco temos uma resposta de confirmação. Resolver isso o mais rápido possível?.

**Comment by joaoalvescs** [comment]
fix #22 @IgorSantos1996 corrigi o bug.

**Comment by IgorSantos1996** [comment]
@joaoalvescs Já que o bug foi resolvido, estou fechando a tarefa Fix#22.
