### ISSUE TITLE
Interface não é responsiva para dispositivos móveis

### ISSUE THREAD

**Issue by joaoalvescs** [marcosdosea/gcm-ufs#26]
O sistema não tem um aplicativo para iOS e Android, devido a esta falta, uma interface responsiva para dispositivos é necessária.

**Comment by igorb22** [comment]
tive problemas ao desenvolver a aplicação para android

**Comment by IgorSantos1996** [comment]
Pretendo me reunir com @igorb22  para desenvolvermos juntos as versões para mobile.

**Comment by igorb22** [comment]
fix #26
