### ISSUE TITLE
O sistema deve enviar e-mail para usuário quando houver atrasos

### ISSUE THREAD

**Issue by igorb22** [marcosdosea/gcm-ufs#27]
O sistema deve enviar e-mail para usuário quando houver atrasos no empréstimo do livro informando valor a pagar.

**Comment by NatanGoes777** [comment]
@igorb22  ja ta enviando

**Comment by igorb22** [comment]
conferido, pode fechar!.

**Comment by NatanGoes777** [comment]
fix #27
