### ISSUE TITLE
Livros novos fora do acervo

### ISSUE THREAD

**Issue by IgorSantos1996** [marcosdosea/gcm-ufs#28]
Foram recebidos livros novos, mas ainda não constam como disponíveis. Atualizar a base de dados.

**Comment by joaoalvescs** [comment]
fix #28 @IgorSantos1996 corrigi o erro e você testará se está tudo funcionando. O código da funcionalidade fix #28

**Comment by joaoalvescs** [comment]
Resolved #28

**Comment by joaoalvescs** [comment]
fix #28

**Comment by joaoalvescs** [comment]
fix #28
