### ISSUE TITLE
O sistema não deve permitir o empréstimo do mesmo livro para usuários distintos

### ISSUE THREAD

**Issue by Kamila-lima** [marcosdosea/gcm-ufs#29]

**Comment by IgorSantos1996** [comment]
@Kamila-lima detalhe a tarefa um pouco mais!

**Comment by valeriabarbosasi** [comment]
Fix @Kamila-lima  O livro será consultado para ver se já está associado a um outro usuário antes de ser emprestado para mais de uma pessoa
