### ISSUE TITLE
Alteração no código para exemplo

### ISSUE THREAD

**Issue by IgorSantos1996** [marcosdosea/gcm-ufs#39]
Alteração no código por João e Igor.

**Comment by joaoalvescs** [comment]
A classe GerenciadorCliente está implementada. #fix39

**Comment by joaoalvescs** [comment]
@IgorSantos1996 por favor, implemente as classes GerenciadorPagamentos.java e GerenciadorVendas.java

**Comment by IgorSantos1996** [comment]
Olá, João. Com dificuldades, ma consegui implementa-las. ;) . Resolve #39

**Comment by IgorSantos1996** [comment]
Cria
