### ISSUE TITLE
Problema no login utilizando caracteres especiais

### ISSUE THREAD

**Issue by victorl1ma** [marcosdosea/gcm-ufs#391]
Ao realizar login de usuário usando caracteres especiais no username, erro indeterminado é exibido na tela.
@davicruzof e @NathanaelSantos  relataram o mesmo erro e solicitou correção urgente devido a gravidade.

**Comment by marcosdosea** [comment]
@victorl1ma  esse é o mesmo problema da issue #380

**Comment by davicruzof** [comment]
Correção realizada com sucesso tanto no front-end como também no back-end
