### ISSUE TITLE
Issues #370 invalid

### ISSUE THREAD

**Issue by davicruzof** [marcosdosea/gcm-ufs#398]
Esse problema foi relatado de forma incorreta, o mesmo deve ser avaliado novamente

**Comment by victorl1ma** [comment]
não posso fazer

**Comment by davicruzof** [comment]
@victorl1ma comparecer no setor de RH no final do dia!

**Comment by JessicaPortilio** [comment]
Problema foi avaliado novamente, feito todas alterações necessários e já foi resolvido.

**Comment by NathanaelSantos** [comment]
Não tenh conhecimento suficiente para fazer a tarefa

**Comment by victorl1ma** [comment]
@marcosdosea  estou sendo ameaçado injustamente aqui.

**Comment by NathanaelSantos** [comment]
Tome ai o número 996084687
