### ISSUE TITLE
Implementar Novos Campos na tabela Aluno

### ISSUE THREAD

**Issue by marcosdosea** [marcosdosea/gcm-ufs#523]
Adicionar os campos nome da mãe e nome de pai para manter esses dados atualizados no histórico do aluno

**Comment by marcosdosea** [comment]
Campos adicionados na tabela Aluno.

**Comment by marcosdosea** [comment]
Close #523

**Comment by marcosdosea** [comment]
Close #523

**Comment by Ericles-Porty** [comment]
👏
