### ISSUE TITLE
Bug ao criar um evento

### ISSUE THREAD

**Issue by Gabrielx47** [marcosdosea/gcm-ufs#528]
Ao criar um evento dentro da ferramenta AgendaOnline e salvá-lo, por consequência, o mesmo não fica registrado no sistema. Dessa forma, deduzo que existe algum problema associado ao salvamento e por isso, é essencial a reparação desta situação .

**Comment by joannestephany** [comment]
Bug removido.
O evento foi revisado e alterações necessárias feitas, as partir do patch 1.7.26 não apresenta mais tal erro
Close https://github.com/marcosdosea/gcm-ufs/issues/528

**Comment by Gabrielx47** [comment]
Show @joannestephany
