### ISSUE TITLE
Quero usar o sistema como um aplicativo mobile.

### ISSUE THREAD

**Issue by Ericles-Porty** [marcosdosea/gcm-ufs#545]
Ficaria grato se o sistema fosse disponibilizado na play store e instalado no meu smartphone.

**Comment by lauro-ss** [comment]
Boas notícias @Ericles-Porty !!!!111 já está em processo de desenvolvimento um aplicativo para dispositivos mobile iOS, então em breve você poderá utilizar e realizar cadastros com a tag " user from iphone ". 

<h5> Esse comentário foi útil para você? Nós envie um feedback. </h5>
