### ISSUE TITLE
Sistema incompatível 

### ISSUE THREAD

**Issue by JorgeMatheuss** [marcosdosea/gcm-ufs#554]
A versão do programa instalada no meu sistema está incompatível.

**Comment by lauro-ss** [comment]
Olá @JorgeMatheuss , sou o @lauro-ss , assistente da equipe de desenvolvimento.

<h1> Soluções para resolver o seu problema. </h1>

<h2> Reinicie a conexão com a internet </h2>
<h3> 1. Desconecte a rede na sua maquina ou dispositivo móvel. </h3>
<h3> 2. Tente novamente. </h3>

<h2> Reinicie o seu dispositivo </h2>
<h3> 1. Aperte o botão reiniciar. </h3>
<h3> 2. Tente novamente. </h3>

<h2> Formate o seu dispositivo </h2>
<h3> 1. Utilizando de algum tutorial realize a formatação. </h3>
<h3> 2. Tente novamente. </h3>

<h2> Compre um novo dispositivo </h2>
<h3> 1. Se dirija a uma loja física ou virtual e compre um novo equipamento. </h3>
<h3> 2. Tente novamente. </h3>

<h2> Construa um novo dispositivo </h2>
<h3> 1. Com algumas ferramentas e conhecimento específico você é capaz de construir seu próprio dispositivo. </h3>
<h3> 2. Tente novamente. </h3>

Com boas soluções, resolvemos o seu problema?
Nós de um feedback 💯
