### ISSUE TITLE
Adicionar coluna na tabela do banco

### ISSUE THREAD

**Issue by MariaMilena** [marcosdosea/gcm-ufs#584]
Adicionar uma coluna com nome de "Observação" para pegar a opinião do cliente sobre os produtos.

**Comment by danknightt** [comment]
Bom dia, @MariaMilena.
Nossa equipe optou em não recolher as informações no banco de dados principal.
Ainda estamos resolvendo essa questão e logo estaremos colocando em prática.
Muito obrigado pelo contato.

**Comment by XxthiagoboyXx** [comment]
Olá Maria Milena, sua requisição foi atendida. Por favor, atualize o nosso aplicativo através da Play Store para habilitar as novas funcionalidades.
