### ISSUE TITLE
Bug na inclusão de clientes

### ISSUE THREAD

**Issue by John0liver** [marcosdosea/gcm-ufs#604]
Corrigir bug quando tenta inserir um novo cliente

**Comment by Kendy619** [comment]
Bug corrigido. Fix #604

**Comment by danknightt** [comment]
Bom dia, John0liver.
Nossa equipe de desenvolvimento já está lidando com o problema e logo logo estará funcionando em perfeito estado.
Agradecemos desde já o contato e comunicado! Tenha um ótimo dia.
#fix
