### ISSUE TITLE
Calcular os valores dos empréstimos do docente.

### ISSUE THREAD

**Issue by gabriel-sisjr** [marcosdosea/gcm-ufs#7]
Calcular os valores dos empréstimos do docente no sistema.

**Comment by igorb22** [comment]
existe alguma diferença no empréstimo para docentes em comparação com o dos alunos ?

**Comment by gabriel-sisjr** [comment]
@igorb22 claro.

**Comment by gabriel-sisjr** [comment]
@igorb22 Adivinhe a regra.

**Comment by Clovijan** [comment]
Fix #7 @gabriel-sisjr já está sendo cobrado o dobro para os docentes.

**Comment by gabriel-sisjr** [comment]
Perfeito @Clovijan , melhor ainda se metade do valor vier para nos
