### ISSUE TITLE
Crie uma branch

### ISSUE THREAD

**Issue by MariaMilena** [marcosdosea/gcm-ufs#787]
Criação da branch

**Comment by Felip3D3V** [comment]
Abra o Terminal ou Prompt de Comando:

Navegue até o diretório do seu repositório Git local.
Atualize o Repositório Local:

Antes de criar uma nova branch, é uma boa prática garantir que seu repositório local esteja atualizado. Execute:
sh
Copiar código
git pull origin main
Substitua main pelo nome da branch padrão do seu repositório, se for diferente (por exemplo, master).
Crie a Nova Branch:

Para criar uma nova branch, use o comando:
sh
Copiar código
git checkout -b nome-da-nova-branch
Substitua nome-da-nova-branch pelo nome que você deseja dar à sua nova branch. Por exemplo:
sh
Copiar código
git checkout -b feature/nova-funcionalidade
Verifique a Criação da Branch:

Verifique se a branch foi criada e você está nela, executando:
sh
Copiar código
git branch
Isso listará todas as branches e a branch atual será marcada com um asterisco (*).
Empurre a Nova Branch para o Repositório Remoto:

Para compartilhar a nova branch com outros membros da equipe, empurre-a para o repositório remoto:
sh
Copiar código
git push -u origin nome-da-nova-branch
