### ISSUE TITLE
Aparecendo foto de lontra no lugar da foto do usuário 

### ISSUE THREAD

**Issue by edutvares** [marcosdosea/gcm-ufs#969]
Ao realizar autenticação a seguinte foto aparece no lugar da foto do usuário

**Comment by paulovsnts** [comment]
![download (1)](https://github.com/marcosdosea/gcm-ufs/assets/88409322/ab6c7cb9-4eb2-4ebc-ba8b-fbc4e20ace80)
Problema resolvido. Agora a foto da lontra foi removida e o usuário aparece dessa forma
